---
title: "hack_data"
author: "Susannah Cowtan"
date: "1 July 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries}
library(readr)
library(dplyr)
library(stringr)
```


```{r globals}
# Focal species
species <- "Hermania scabra"
# Dataset
dataset_id <- "2462ab76-f01f-4c2c-bf00-1cae962f386a"

# Data file locations
filepath = "../../talk_data/"
intpath = "../../int_data/"

# Restrictions
min_year <- 1880
# Within the rectangle containing the Kattegat
lat_minmax <- c(54.75, 57.95)
long_minmax <- c(9.90, 12.85)
```

```{r generate_filenames}
filename_ds <- paste0(filepath, "occ_shark_old.csv")
filename_new <- paste0(filepath, "shark.csv")
```

```{r read_shark, echo=FALSE}
# Don't query OBIS if we don't have to
if(!file.exists(filename_ds)) {
  shark_df <- occurrence(datasetid = dataset_id)
  write_csv(shark_df, filename_ds)
} else {
  # cols() guesses wrong if rows at the top are NA
  shark_df <- read_csv(filename_ds, col_types = cols(
    section = col_character(), subsection = col_character(),
    subtribe = col_character(),
    sectionid = col_double(), subsectionid = col_double(),
    subtribeid = col_double()
  ))
}
```

```{r}
names(shark_df)

```


```{r write}
shark_df %>%
  select(scientificName, year, decimalLatitude, decimalLongitude) %>%
  filter(str_detect(scientificName, "^[A-Z][a-z]+[:space:][a-z]+$")) %>%
  write_csv(filename_new)
```

